---
- name: Set router banners
  hosts: all
  gather_facts: false

  tasks:
    - name: Load banner onto network device
      vars:
        - network_banner: "{{ net_banner | default(None) }}"
        - banner_type: "{{ net_type | default('login') }}"
      ansible.builtin.include_role:
        name: "../roles/banner"
